version: 2

jobs:
  lint-go:
    docker: &docker_go
      - image: circleci/golang:1.11
    environment: &env_go
      GOPATH: /home/circleci/go
    working_directory: /home/circleci/go/src/github.com/Gameye/gameye-sdk-go
    steps:
      - checkout
      - run: go get golang.org/x/lint/golint
      - run: golint -set_exit_status ./...

  test-go:
    docker: *docker_go
    environment: *env_go
    working_directory: /home/circleci/go/src/github.com/Gameye/gameye-sdk-go
    steps:
      - checkout
      - run: go get -t ./...
      - run: go test -v ./...

  vet-go:
    docker: *docker_go
    environment: *env_go
    working_directory: /home/circleci/go/src/github.com/Gameye/gameye-sdk-go
    steps:
      - checkout
      - run: go get -t ./...
      - run: go vet ./...

workflows:
  version: 2
  go:
    jobs:
      - lint-go: &go_job
          filters:
            branches:
              only: /.*?/
            tags:
              only: /.*?/
      - test-go: *go_job
      - vet-go: *go_job
