version: 2

jobs:
  prepare:
    docker: &docker_golang
      - image: circleci/golang:1.10
    environment:
      GOPATH: /home/circleci/go
    working_directory: /home/circleci/go/src/github.com/Gameye/gameye-sdk-node
    steps:
      - checkout
      - run: dep ensure
      - persist_to_workspace:
          root: .
          paths:
            - vendor

  lint:
    docker: *docker_golang
    environment:
      GOPATH: /home/circleci/go
    working_directory: /home/circleci/go/src/github.com/Gameye/gameye-sdk-node
    steps:
      - checkout
      - run: go get golang.org/x/lint/golint
      - run: ~/go/bin/golint ./clients ./models ./selectors ./test ./utils

  spec:
    docker: *docker_golang
    environment:
      GOPATH: /home/circleci/go
    working_directory: /home/circleci/go/src/github.com/Gameye/gameye-sdk-node
    steps:
      - checkout
      - attach_workspace: *attach_workspace
      - run: go get github.com/jstemmer/go-junit-report
      - run: mkdir -p /tmp/test-results
      - run: go test ./clients ./models ./selectors ./test ./utils -v | ~/go/bin/go-junit-report > /tmp/test-results/spec.xml
      - store_test_results: &store_test_results
          path: /tmp/test-results

workflows:
  version: 2
  main:
    jobs:
      - prepare:
          filters: &filter_all
            tags:
              only: /.*?/
      - lint:
          requires: [ prepare ]
          filters: *filter_all
      - spec:
          requires: [ prepare ]
          filters: *filter_all
