version: 2

jobs:
  lint-go:
    docker: &docker_go
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: go get golang.org/x/lint/golint
      - run: golint -set_exit_status ./pkg/...

  test-go:
    docker: *docker_go
    steps:
      - checkout
      - run: go get -t ./pkg/...
      - run: go test -v ./pkg/...

  vet-go:
    docker: *docker_go
    steps:
      - checkout
      - run: go get -t ./pkg/...
      - run: go vet ./pkg/...

workflows:
  version: 2
  go:
    jobs:
      - lint-go: &go_job
          filters:
            branches:
              only: /.*?/
            tags:
              only: /.*?/
      - test-go: *go_job
      - vet-go: *go_job
